spring.application.name=biblioteca2026

spring.datasource.url=jdbc:postgresql://localhost:5432/biblioteca2026
spring.datasource.username=postgres
spring.datasource.password=postdba

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true